language: node_js
node_js:
- 6.9.2
deploy:
  provider: npm
  api_key:
    secure: Ct1Rv8yYbsBZ+7rz86CwMIUlDyhq0IkxNFXslorpcsJYeF92zPoPh08uaTc1f6Jyt0BP3owbX/n+IH99eR0aioZrzxlDapum9B4q+rfeCLH+rtrwwb0IqRwnK0TXfPLg/CBEbk6U+Rw16Eq0CMbLnwtOy9nkkiPptbOH9Ph/SuTDdAdXt2V64c9NfMEGgywQYFVzPEOgnmn4IT1w3gdDPN8nRbKkOkv0cSRJyENjwyc+lolUeZBnu6ZTegMtIeTVnn9iPhXgHzb9vjXORtLXr6u4qIiOcC/cfg8deMZqLF/2gQKbyOyQ48cJKap7vFGe4UY6GGK7y18T9mjHmw3yp88+miDF0g3w+mTye7gY9+TDl6FS5WaGAi2BuF9elnTX23ZSjBrOX3/im3sfdEJmEB7pTk30x3gfCzptqUhoS5XbirkXdlrN2sgnbkcBoYTxpUEBho9lWozh9B0oJp97wjBgZtrgBlSuAMMP3NoEUtr7VfWvOpuIvYevFMGN9uVZfnWSfgKyuPVMTCu51kNkfXzmuyt4JXlYM7QfJfTje0X0nMZ5S3HZItsacX+z4qFYRyJGdb6yqy/sVTII54T5s0twkJ5jw2mqKT2i/FTZOwnp1ziAilxm12PQJnHqoG1NzCVoB9z/gOoJzqmQGYj2DFEW7SvKfl5tgY2XZtZlzRU=
  on:
    all_branches: true
    tags: true
    repo: bealearts/concurrent-file-store
